---
  - name: build hosts file
    lineinfile:
      dest: /etc/hosts
      insertafter: EOF
      line: '{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }} {{ ansible_hostname }}.{{ ansible_domain }}'
      state: present